# Docker Compose 文件版本，定义了配置文件的语法版本
version: '3.8'

services:
  # 前端服务配置
  frontend:

    # 使用的 Docker 镜像名称和标签
    image: holic512/sloth-note-frontend:latest
    # 将容器的 80 端口映射到主机的 8081 端口
    ports:
      - "8081:80"
    # 将前端服务连接到名为 sloth-note-network 的自定义网络
    networks:
      - sloth-note-network

  # 后端服务配置
  backend:

    # 使用的 Docker 镜像名称和标签
    image: holic512/sloth-note-backend:latest

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://192.168.188.36:3306/SlothNote
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: m13245jia

      SPRING_REDIS_HOST: 192.168.188.36
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: 123456

      SPRING_MONGODB_HOST: 192.168.188.36
      SPRING_MONGODB_PORT: 27017
      SPRING_MONGODB_DATABASE: SlothNote
      SPRING_MONGODB_USERNAME: mongo_holic
      SPRING_MONGODB_PASSWORD: mongo_holic
      SPRING_MONGODB_AUTHENTICATION_DATABASE: admin

      SPRING_RABBITMQ_HOST: 192.168.188.36
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: rabbitmq
      SPRING_RABBITMQ_PASSWORD: rabbitmq

    # 将后端服务连接到名为 sloth-note-network 的自定义网络
    networks:
      - sloth-note-network

# 自定义网络配置
networks:
  # 定义 sloth-note-network 网络，使用 bridge 驱动进行容器间通信
  sloth-note-network:
    driver: bridge
