# Docker Compose 文件版本，定义了配置文件的语法版本
version: '3.8'

services:
  # 前端服务配置
  frontend:
    # 使用的 Docker 镜像名称和标签
    image: sloth-note-frontend:latest
    # 将容器的 80 端口映射到主机的 8081 端口
    ports:
      - "8081:80"
    # 将前端服务连接到名为 sloth-note-network 的自定义网络
    networks:
      - sloth-note-network

  # 后端服务配置
  backend:
    # 使用的 Docker 镜像名称和标签
    image: sloth-note-backend:latest
    # 将容器的 8080 端口映射到主机的 8080 端口
    ports:
      - "8080:8080"
    # 将后端服务连接到名为 sloth-note-network 的自定义网络
    networks:
      - sloth-note-network

# 自定义网络配置
networks:
  # 定义 sloth-note-network 网络，使用 bridge 驱动进行容器间通信
  sloth-note-network:
    driver: bridge
