# 生产环境变量
spring:

  sql:
    init:
      mode: always
      schema-locations: classpath*:sql/createTable/*.sql

  # 数据库设置
  datasource:
    url: jdbc:mysql://${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    # redis配置
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD}

    # mongodb配置
    mongodb:
      host: ${SPRING_MONGODB_HOST}
      port: ${SPRING_MONGODB_PORT}
      database: ${SPRING_MONGODB_DATABASE}
      username: ${SPRING_MONGODB_USERNAME}
      password: ${SPRING_MONGODB_PASSWORD}
      authentication-database: ${SPRING_MONGODB_AUTHENTICATION_DATABASE:admin}

  # rabbit 配置
  rabbitmq:
    port: ${SPRING_RABBITMQ_PORT}
    host: ${SPRING_RABBITMQ_HOST}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

