CREATE TABLE admins
(
    id         BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '主键 ID',
    uid        VARCHAR(50)  NOT NULL UNIQUE COMMENT '用户 ID',
    username   VARCHAR(50)  NOT NULL UNIQUE COMMENT '用户名',
    password   VARCHAR(255) NOT NULL COMMENT '密码',
    email      VARCHAR(100) NOT NULL UNIQUE COMMENT '邮箱',
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '账户创建时间',
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '信息更新时间'
);
